Repository jenkinsci/branch-api-plugin, pull requests merged in 2024-02, with the labels that each got.

#433 [JENKINS-72026] Fix jumping icons in narrow view
  src/main/resources/jenkins/branch/ItemColumn/column.jelly
Labels: bug, ui

#435 Make `NoTriggerBranchPropertyTest` pass against 2.446
  src/test/java/jenkins/branch/NoTriggerBranchPropertyTest.java
Labels: developer

#437 Remove references to deprecated `ANTLRException`
  src/main/java/jenkins/branch/OrganizationChildTriggersProperty.java
  src/main/java/jenkins/branch/OrganizationFolder.java
Labels: internal
