Repository jenkinsci/branch-api-plugin, pull requests merged in 2024-10, with the labels that each got.

#490 [JENKINS-73947] Improve CSP compatibility
  src/main/resources/jenkins/branch/PropertyMigration/MonitorImpl/branch-api-property-migration-disabled-form.js
  src/main/resources/jenkins/branch/PropertyMigration/MonitorImpl/message.jelly
Labels: internal

#476 [JENKINS-60082] Show pull request title in name column
  src/main/java/jenkins/branch/ItemColumn.java
  src/main/java/jenkins/branch/MultiBranchProject.java
  src/main/java/jenkins/branch/MultiBranchProjectDisplayNamingStrategy.java
  src/main/resources/jenkins/branch/ItemColumn/column.jelly
  src/test/java/integration/CategorizationTest.java
Labels: enhancement

#492 [JENKINS-74783] Fix job name line break behavior in Firefox
  src/main/resources/jenkins/branch/ItemColumn/column.jelly
Labels: bug
